### ISSUE TITLE
打开环境报错

### ISSUE THREAD

**Issue by Air-legend** [inspirai/wilderness-scavenger#11]
OSError: dlopen(/Users/mxj/digisky/qiyuan/wilderness-scavenger/inspirai_fps/lib/libraycaster.dylib, 0x0006): tried: '/Users/mxj/digisky/qiyuan/wilderness-scavenger/inspirai_fps/lib/libraycaster.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h'))

**Comment by FateDawnLeon** [comment]
目前射线库运行暂不支持非x86架构机器，请转移到其他符合条件的机器运行

**Comment by Air-legend** [comment]
表示难过😫
