### ISSUE TITLE
Navigation Track中 agent返回的movespeed数据异常

### ISSUE THREAD

**Issue by chenjinghs** [inspirai/wilderness-scavenger#12]
请问 在Navigation Track中 agent返回的movespeed数据好像异常。

输入action为 walkdir [0, 90,180,270] walkspeed [3, 6] turn_lr [-3, 0 ,3]

打印发现agent movespeed 从0递增到 3000+ 而非说明中的 m/s 

环境是 linux 的backend【5.16】

**Comment by FateDawnLeon** [comment]
你好，感谢提问，麻烦提供一下运行的代码段，以及打印的结果，我们尽快排查

**Comment by chenjinghs** [comment]
不好意思，我发现是应为机器人出生的地点在地面以下下坠导致的速度过大， 请问是否能提供获取地图特定地点地表的高度值的接口，这样方便我们自主的设置机器人出生的地点，虽然接口中提供了随机的出生地点，但这样会更加灵活。谢谢

**Comment by FateDawnLeon** [comment]
很抱歉，目前暂时无法支持这种高度查询，我们的建议是：

1. 使用get_valid_locations接口获取所有合法的出生点位，再根据需要进行筛选；
2. 或者设置出生点位时，设定一个较大的y值（例如y=10，但是依然无法保证不会初始化在地面以下）

希望对你有帮助，谢谢！
