### ISSUE TITLE
A little bug in gamecore.py ?

### ISSUE THREAD

**Issue by JYLiAo32** [inspirai/wilderness-scavenger#13]
gamecore.py 第155行代码：`self.dir_vec = dir_vec / np.linalg.norm(self.dir_vec)`

应该是 `self.dir_vec = dir_vec / np.linalg.norm(dir_vec)` 吧？

**Comment by FateDawnLeon** [comment]
感谢提问，这里确实有点问题，不过我们目前没有使用 `EnemyStateRough` 这个class，所以应该不影响运行
