### ISSUE TITLE
is it possible headless mode?

### ISSUE THREAD

**Issue by LeejwUniverse** [inspirai/wilderness-scavenger#19]
HI, inspirai.

I'm trying to train my model. I wonder is it possible headless mode? because, Unity enviornment is paused frequently. I had to click client for tackling this problem always... when I trained on windows.
In case of linux version, can possible headlees mode?

**Comment by FateDawnLeon** [comment]
Hi, Leejw,

Thank you for the question. I am not sure if you are saying that windows version of the backend periodically stops running? In my experience, I did not encounter that often. But in case you do have the problem, we recommend you switching to the linux backend, which is tested more extensively and you shall probably not have this issue any more.

**Comment by LeejwUniverse** [comment]
Hi, FateDawnLeon

I tried to switch a backend from windows to linux. however in my case, track2 battle senario occured a problem that the simulator was paused frequently when I trained Agent on windows and linux.
other track is fine.

thanks.

**Comment by FateDawnLeon** [comment]
Hi, LeejwUniverse

I guess maybe the problem is that you set more than one `supply_refresh` events in a game episode. As we have tested, this may slow down the game significantly. We suggest you always have no more than one `supply_refresh` event when running the game.

Thanks.
