### ISSUE TITLE
Is the depth map available for all tracks?

### ISSUE THREAD

**Issue by yoshinobc** [inspirai/wilderness-scavenger#20]
I checked `submission_template/eval_track_1_1.py` and `game.turn_on_depth_map()` is not called, so `state.depth` is `None` (same for other trucks).

Since `game.set_depth_map_size(DEPTH_MAP_WIDTH, DEPTH_MAP_HEIGHT, DEPTH_MAP_FAR)` is called, it seems that the depth map is available, right?

**Comment by FateDawnLeon** [comment]
Yes, you can access the depth map for all 3 tracks.
