### ISSUE TITLE
Windows环境问题2

### ISSUE THREAD

**Issue by chawuchen** [inspirai/wilderness-scavenger#5]
gamecore.py中，600行
            self.engine_process = subprocess.Popen(cmd.split(),stdout=f, stderr=f)
应当增加shell=True，否则没法启动backend，会报错[WinError 2] 系统找不到指定的文件。

**Comment by 945716994** [comment]
添加了以后，启动了，但是会报这个错误： FileNotFoundError: Could not find module 'D:\CODE\wilderness-scavenger-master\inspirai_fps\lib\raycaster.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by FateDawnLeon** [comment]
- [x] 解决启动问题：添加 `shell=True`
- [ ] `FileNotFoundError`: 这个问题应该是由于python3.8以后的cdll加载保护机制造成的，目前还在排查，大佬想快速解决可以参考这里 [link](https://github.com/ynyyn/Miniblink-Python-SimpleDemo/issues/4)。如有解决成功也希望在这里分享一下，谢谢！

**另外强烈建议windows用户使用WSL2运行训练环境，直接使用Linux的Engine backend**
