### ISSUE TITLE
State里真的没有pixel信息吗

### ISSUE THREAD

**Issue by chawuchen** [inspirai/wilderness-scavenger#6]
不管是在Readme中写的Agent State Variable还是代码中都没有看到任何的RGB pixel信息，
只有postion和direction, 还有深度图
感觉跟传统意义上理解的fps环境不太一样

**Comment by FateDawnLeon** [comment]
感谢提问，我们本次比赛的环境是不直接提供RGB图像信息的，一方面是因为环境的图形渲染会极大增加训练和推理的开销，成为潜在的参赛门槛，另外根据我们以往的实践经验，利用角色状态信息和深度图已经足够学习复杂多样的游戏策略，所以增加RGB图像的必要性并不明显。希望回复对您有帮助，祝参赛愉快！
