### ISSUE TITLE
关于评测的问题

### ISSUE THREAD

**Issue by Rinstein** [inspirai/wilderness-scavenger#9]
请问目前各个赛道的评测是否已经确定，比如赛道1，其env_track1.py中定义的动作空间和观测空间过于简单，动作空间只有方向和速度，那么如果目标点在楼顶，则无法到达，因为没有jump动作。赛道2的多人对抗环境还没有定义，那么这部分封装gym环境是我们自己来做吗？

**Comment by FateDawnLeon** [comment]
1. 各个赛道评测时可以使用的动作空间在我们的网站介绍上有详细描述 [ActionTable](https://lh5.googleusercontent.com/ANqKjmpn2heJtDl6HOtPU528-WEyRwO3kjJk96f2iv3UGP0fUoHGSqRLciiram4f_RC1qLFeOQ7ZtIng2vJX36Tc61MbF7kOI7CNsd0Chw-8A8W02-_8aAzXsbooaO5pRA=w1280)
2. 各赛道的评测方式还在设计中，预计会在下周发布
3. 关于观测空间：我们不会给出固定的观测空间设计，但是参赛者可以自由使用AgentState里面的属性自行构建观测空间，评测时也会把AgentState作为提交的控制策略的输入
